<?php
require_once __DIR__ . '/includes/manager_context.php';
?>
<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Team Roster | SmartStaff</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="manager-layout">
<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">SS</span><span>SmartStaff</span></div><nav class="nav-menu" aria-label="Manager workspace"><span class="nav-section-label">Manager workspace</span><a href="manager_overview.php" class="nav-link"><span class="nav-link-icon">OV</span>Overview</a><a href="manager_attendance.php" class="nav-link"><span class="nav-link-icon">AT</span>Team attendance</a><a href="manager_approvals.php" class="nav-link"><span class="nav-link-icon">AP</span>Approvals</a><a href="manager_roster.php" class="nav-link active" aria-current="page"><span class="nav-link-icon">TR</span>Team roster</a></nav><div class="sidebar-footer"><p><?php echo htmlspecialchars($manager['name']); ?></p><a href="logout.php" class="logout-link">Log out</a></div></aside>
<main class="main-panel"><header class="topbar"><div><p class="eyebrow accent">Manager module</p><h1>Team roster</h1></div><div class="topbar-user"><div class="avatar-circle"><?php echo htmlspecialchars($manager['avatar']); ?></div><span><?php echo htmlspecialchars($manager['role']); ?></span></div></header><section class="panel manager-module-heading"><p class="eyebrow accent">Your direct reports</p><h2>Team roster</h2><p>Review manager-only work summaries for the people assigned to you.</p></section><section class="panel"><div class="panel-header"><h3>Direct reports</h3><span class="badge"><?php echo count($team); ?></span></div><div class="list-table"><?php if (empty($team)): ?><p class="empty-state">No direct reports assigned yet.</p><?php else: ?><?php foreach ($team as $person): ?><details class="manager-team-member"><summary class="list-row"><div><strong><?php echo htmlspecialchars($person['name']); ?></strong><small><?php echo htmlspecialchars($person['role']); ?> · <?php echo htmlspecialchars($person['department']); ?></small></div><span class="mini-btn approve">View summary</span></summary><div class="manager-member-summary"><span><strong>Location</strong><?php echo htmlspecialchars($person['location'] ?? 'Office'); ?></span><span><strong>Employment</strong><?php echo htmlspecialchars($person['employment_type'] ?? 'Full-time'); ?></span><span><strong>Schedule</strong><?php echo htmlspecialchars($person['shift_time'] ?? 'Not provided'); ?></span><span><strong>Status</strong><?php echo htmlspecialchars($person['status'] ?? 'Active'); ?></span></div></details><?php endforeach; ?><?php endif; ?></div></section></main></div>
</body></html>
